name: GitHub Metrics - Achievements Compact

# limit default GITHUB_TOKEN permissions
permissions:
  contents: read

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4   # uses default GITHUB_TOKEN (safe for checkout)
      - uses: lowlighter/metrics@latest
        with:
          # Use a PAT stored in repository secrets
          token: ${{ secrets.GIT_HUB }}
          user: yerijhonrian
          base: ""
          filename: metrics.achievements.svg
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
          plugin_achievements_only: >-
            polyglot,
            stargazer,
            sponsor,
            deployer,
            member,
            maintainer,
            developer,
            scripter,
            packager,
            explorer,
            infographile,
            manager
      - name: Commit and push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add metrics.achievements.svg
          git commit -m "Update achievements metrics" || echo "No changes to commit"
          git push