name: GitHub Metrics - Achievements Compact

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate achievements metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GIT_HUB }}

          user: yerijhonrian
          base: ""
          filename: metrics.achievements.svg

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: 1

          plugin_achievements_only: >-
            polyglot,
            stargazer,
            sponsor,
            deployer,
            member,
            maintainer,
            developer,
            scripter,
            packager,
            explorer,
            infographile,
            manager

      - name: Commit and push metrics
        run: |
          git status
          git add metrics.achievements.svg
          git commit -m "Update achievements metrics" || echo "No changes"
          git push
